import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import Homepage from '../src/components/home/home'
import Footer from '../src/components/footer/footer'
import Header from '../src/components/header/header'

const inter = Inter({ subsets: ['latin'] })

export default function Home({data}) {
  return (
    <div>
      
      <Head>
        <title>Next JS APP</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Homepage data={data}/>

    </div>
  )
}

export async function getServerSideProps() {
  const {events_categories} = await import('/data/db.json')

  return{
      props:{
          data: events_categories,
      }
  }
}
